// Mocks generated by Mockito 5.4.4 from annotations
// in life_shared/test/day_of_time_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:life_shared/src/models/category_model.dart' as _i4;
import 'package:life_shared/src/models/store_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStoreModel_0 extends _i1.SmartFake implements _i2.StoreModel {
  _FakeStoreModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StoreModel].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockStoreModel extends _i1.Mock implements _i2.StoreModel {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  String get owner => (super.noSuchMethod(
        Invocation.getter(#owner),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#owner),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#owner),
        ),
      ) as String);

  @override
  String get phone => (super.noSuchMethod(
        Invocation.getter(#phone),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#phone),
        ),
      ) as String);

  @override
  List<String> get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  int get townCode => (super.noSuchMethod(
        Invocation.getter(#townCode),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int get visitCount => (super.noSuchMethod(
        Invocation.getter(#visitCount),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isApproved => (super.noSuchMethod(
        Invocation.getter(#isApproved),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get documentId => (super.noSuchMethod(
        Invocation.getter(#documentId),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#documentId),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#documentId),
        ),
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
        returnValueForMissingStub: <Object?>[],
      ) as List<Object?>);

  @override
  _i2.StoreModel copyWith({
    String? name,
    String? owner,
    String? description,
    String? address,
    String? phone,
    List<String>? images,
    int? townCode,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? isApproved,
    String? deviceID,
    String? documentId,
    _i4.CategoryModel? category,
    int? visitCount,
    String? openTime,
    String? closeTime,
    _i5.GeoPoint? latLong,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #name: name,
            #owner: owner,
            #description: description,
            #address: address,
            #phone: phone,
            #images: images,
            #townCode: townCode,
            #createdAt: createdAt,
            #updatedAt: updatedAt,
            #isApproved: isApproved,
            #deviceID: deviceID,
            #documentId: documentId,
            #category: category,
            #visitCount: visitCount,
            #openTime: openTime,
            #closeTime: closeTime,
            #latLong: latLong,
          },
        ),
        returnValue: _FakeStoreModel_0(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #name: name,
              #owner: owner,
              #description: description,
              #address: address,
              #phone: phone,
              #images: images,
              #townCode: townCode,
              #createdAt: createdAt,
              #updatedAt: updatedAt,
              #isApproved: isApproved,
              #deviceID: deviceID,
              #documentId: documentId,
              #category: category,
              #visitCount: visitCount,
              #openTime: openTime,
              #closeTime: closeTime,
              #latLong: latLong,
            },
          ),
        ),
        returnValueForMissingStub: _FakeStoreModel_0(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #name: name,
              #owner: owner,
              #description: description,
              #address: address,
              #phone: phone,
              #images: images,
              #townCode: townCode,
              #createdAt: createdAt,
              #updatedAt: updatedAt,
              #isApproved: isApproved,
              #deviceID: deviceID,
              #documentId: documentId,
              #category: category,
              #visitCount: visitCount,
              #openTime: openTime,
              #closeTime: closeTime,
              #latLong: latLong,
            },
          ),
        ),
      ) as _i2.StoreModel);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.StoreModel fromFirebase(
          _i5.DocumentSnapshot<Map<String, dynamic>>? snapshot) =>
      (super.noSuchMethod(
        Invocation.method(
          #fromFirebase,
          [snapshot],
        ),
        returnValue: _FakeStoreModel_0(
          this,
          Invocation.method(
            #fromFirebase,
            [snapshot],
          ),
        ),
        returnValueForMissingStub: _FakeStoreModel_0(
          this,
          Invocation.method(
            #fromFirebase,
            [snapshot],
          ),
        ),
      ) as _i2.StoreModel);

  @override
  _i2.StoreModel fromJson(Map<String, dynamic>? json) => (super.noSuchMethod(
        Invocation.method(
          #fromJson,
          [json],
        ),
        returnValue: _FakeStoreModel_0(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
        returnValueForMissingStub: _FakeStoreModel_0(
          this,
          Invocation.method(
            #fromJson,
            [json],
          ),
        ),
      ) as _i2.StoreModel);
}
