name: life_shared
description: A new Flutter package project.
version: 0.0.1
homepage: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_image_compress: ^2.0.4
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  image_picker: ^1.0.4
  image_cropper: ^7.0.5

  #firebase
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.6
  firebase_ui_firestore: ^1.6.2

  # Util
  logger: ^2.0.2
  kartal: ^4.0.4
  uuid: ^4.3.3
  collection: ^1.18.0

  # UI
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  very_good_analysis: ^5.1.0

flutter:
